### ISSUE TITLE
Doesn't seem to work now (Win 10 / Firefox 77)

### ISSUE THREAD

**Issue by RiteshSingh** [skygate2012/i_would_like_to_obtain_a_sample_plox#2]
Thank you for your effort.

But this doesn't seem to work now.

**Comment by skygate2012** [comment]
Duplicate of #1 
Please use Firefox 68.9.0esr, I haven't found a way to solve this issue yet.

**Comment by RiteshSingh** [comment]
Update: **Works in Firefox 70.0.1**

Thank you!!
