### ISSUE TITLE
I Need your help. It is important.

### ISSUE THREAD

**Issue by systemvevo** [skygate2012/i_would_like_to_obtain_a_sample_plox#4]
Hi , first of all thanks for add-on. I downloaded this 3 months ago. plugin was running at that 3 months ago.

But today , it is not responding, mozilla add on page is says "can’t find that page" .

Please help me sir. I need to download voices from Google text to speech, for my univercity exam. How can i do now ?

**Comment by skygate2012** [comment]
1. Download Firefox ESR 68.12.0
2. Download this repository
3. Follow [this instruction](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) to load it into the browser

**Comment by systemvevo** [comment]
> 1. Download Firefox ESR 68.12.0
> 2. Download this repository
> 3. Follow [this instruction](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) to load it into the browser

I Will make it. Thank you for help , really appreciative it.
